<?php

namespace Samsin33\DecisionEngine\Models;

use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Model;
use Samsin33\DecisionEngine\DecisionEngine;

class RuleExecutionLog extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'rule_execution_logs';

    /**
     *
     * @var array<string>
     */
    protected $fillable = ['rule_execution_id', 'previous_attributes', 'new_attributes'];

    /**
     *
     * @var array<string>
     */
    protected $visible = ['id', 'rule_execution_id', 'previous_attributes', 'new_attributes', 'created_at', 'updated_at'];

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub

        self::creating(function () {
            $this->ipaddress = request()->ip();
        });
    }

    //--------------------- Relationships ------------------------------

    /**
     *
     * @return BelongsTo
     */
    public function ruleExecution(): BelongsTo
    {
        return $this->belongsTo(DecisionEngine::$ruleExecutionModel, 'rule_execution_id', 'id');
    }
}
