<?php

namespace Samsin33\DecisionEngine\Models;

use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\MessageBag;
use Illuminate\Validation\Rule;
use Samsin33\DecisionEngine\DecisionEngine;

class RuleExecution extends Model
{
    /**
     * @var MessageBag|null $errors
     */
    private ?MessageBag $errors = null;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'rule_executions';

    /**
     *
     * @var array<string>
     */
    protected $fillable = ['rule_engine_id', 'input', 'output', 'status'];

    /**
     *
     * @var array<string>
     */
    protected $visible = ['id', 'rule_engine_id', 'input', 'output', 'status', 'created_at', 'updated_at'];

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub

        self::creating(function ($rule_execution) {
            $rule_execution->created_by = Auth::user()->id ?? null;
            $rule_execution->status = 'Begin Execution';
            $rule_execution->ipaddress = request()->ip();
        });

        self::saving(function ($rule_execution) {
            $validates = Validator::make($rule_execution->getAttributes(), $rule_execution->getValidationRules());
            if ($validates->fails()) {
                $rule_execution->errors = $validates->errors();
                return false;
            }
            return $rule_execution;
        });

        self::updated(function ($rule_execution) {
            $execution_log = DecisionEngine::ruleExecutionLog(['previous_attributes' => $rule_execution->getOriginal(), 'new_attributes' => $rule_execution->getDirty()]);
            $execution_log->save();
        });
    }

    //--------------------- Validations --------------------------------

    /**
     *
     * @return array
     */
    public function getValidationRules(): array
    {
        return [
            'rule_engine_id' => ['required',
                Rule::exists(config('decision-engine.db_connection').'.rule_engines', 'id'),
            ],
            'input' => ['required', 'array'],
            'status' => ['string',
                Rule::requiredIf(function () {
                    return $this->id > 0;
                }),
            ],
        ];
    }

    /**
     * @return MessageBag
     */
    public function getErrors(): MessageBag
    {
        return $this->errors ?? new MessageBag();
    }

    //--------------------- Relationships ------------------------------

    /**
     *
     * @return BelongsTo
     */
    public function ruleEngine(): BelongsTo
    {
        return $this->belongsTo(DecisionEngine::$ruleEngineModel, 'rule_engine_id', 'id');
    }

    /**
     * @return HasMany
     */
    public function ruleExecutionLogs(): HasMany
    {
        return $this->hasMany(DecisionEngine::$ruleExecutionLogModel, 'rule_execution_id', 'id');
    }
}
